# This is python  numpy
Numpy is the array package,it is provide a high performance multidimensional array objects
numpy is the homegenious multidimensional array. numpy dimension is also called axes

For example, the coordinates of a point in 3D space [1, 2, 1] has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

[[1,4,2],
 [3,5,6]]
NumPy’s array class is called ndarray. It is also known by the alias array.

#this indicate hoe many axes in the array for ex .. one,two ... multidimensional array
arr1.ndim
#which is indicate how many rows and column appears in the specified array
arr1.shape



In [2]:
import numpy as np
arr1=np.arange(15).reshape(3,5)
arr1
#this indicate how many axes in the array for ex .. one,two ... multidimensional array
arr1.dtype
arr1.itemsize




4

In [3]:
type(arr1)

numpy.ndarray

In [4]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"


[[0. 0.]
 [0. 0.]]


In [5]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"


[[1. 1.]]


In [6]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"


[[7 7]
 [7 7]]


In [7]:
d= np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
e =np.random.random((2,3))
e

array([[0.64204849, 0.55676597, 0.73305308],
       [0.76862177, 0.36274692, 0.25693219]])

In [9]:
between_values = np.arange(2,4,0.2)
between_values

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8])

In [10]:
new = np.array([1,2,3,4,5])
cd = new[1:4]
cd

array([2, 3, 4])

In [11]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [12]:
b[0, 0]

2

In [13]:
two_arr = np.array([[1,2],[4,5],[2,5]])
get = two_arr[:2,1:]
get


array([[2],
       [5]])

# multidimensional array


In [14]:
mul_dim = np.array([[[1,2,3,4], [5,6,7,8], [9,10,11,12]]])
mul_dim


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [15]:
mul_dim.ndim

3

In [16]:
newarr = mul_dim[1:,:,:1]
newarr

array([], shape=(0, 3, 1), dtype=int32)

In [25]:
mylist = [[10,20,30],[40,50,60],[70,80,90]]
arr = np.array(mylist)
print("elements")
for row in arr:
    for ele in row:
        print(ele ,end = ' ')
    print()
    

elements
10 20 30 
40 50 60 
70 80 90 


In [27]:
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [34]:
newarray = arr[:,1:]
print(newarray)

[[50 60]
 [80 90]]
